### ISSUE TITLE
Autobuild decision

### ISSUE THREAD

**Issue by mateus2022git** [Anbeeld/ARoAI#2]
when I activate the decision the options appear invalid

said "ec_open_autobuild_settings"

the "options "ARoAI_economy_events.6.1a" etc...

[17:45:12][pdx_persistent_reader.cpp:252]: Error: "Failed to read key reference: si_economic_system_automation: si_economic_system_automation, near line: 1

**Comment by mateus2022git** [comment]
ops I missed this one, I have to create line codes

**Comment by Anbeeld** [comment]
Some kind of conflict with Improved Automation. You seem to use an older version of it. I just tried the latest version and it's totally fine.
