### ISSUE TITLE
Improve repo structure

### ISSUE THREAD

**Issue by alexbeloi** [Anbeeld/ARoAI#3]
Hey, thanks for working on this mod, it improves the gameplay experience and challenge considerably.

I would like to contribute some changes if you're open to looking at pull requests.

It would make it easier if the repo was structured like more traditional coding projects. For example

1. having the mod code in the repo rather than a zip file. (hard to look at diffs between versions with a zip file)
2. managing releases using github's release mechanism: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository. And create zips for releases with https://github.com/marketplace/actions/zip-release

I can set this up in a fork and make a PR if you don't have time for it.

**Comment by Anbeeld** [comment]
That's by design. It's just a download hub at the moment. If you have something to suggest, there are a lot of ways to contact me.
